FROM node:20

COPY package.json /app/
COPY package-lock.json /app/
COPY server/package.json /app/server/
COPY client/package.json /app/client/
COPY common/package.json /app/common/

RUN npm config set fetch-retries 4
RUN npm config set fetch-timeout 500000
RUN npm config set fetch-retry-maxtimeout 100000 
RUN npm config set fetch-retry-mintimeout 20000 

RUN npm i --prefix app
